### ISSUE TITLE
Network interfaces are down

### ISSUE THREAD

**Issue by woundride** [bmn-m/Stormshield-SN300-openwrt#1]
Hi,

Thanks for this great tip !
I've doing installation on my SN300 but network interfaces are down :/
With ifconfig I can see eth0 is up, driver used is e1000e (verified with ethtool).
Have you define specific option in network configuration ?

Best regards,

Charles

**Comment by bmn-m** [comment]
Hi,
[this](https://github.com/bmn-m/Stormshield-SN300-opnsense#switching)
should solve your Problem.
Unfortunately, I no longer have the devices with me on site to look at it again. 
Best regards,
Matthias

**Comment by woundride** [comment]
Thanks for your prompt reply Matthias !
After some efforts, it work !!!
