### ISSUE TITLE
Network file

### ISSUE THREAD

**Issue by devjochem** [bmn-m/Stormshield-SN300-openwrt#3]
In the readme you talk about a network config file. Where is the file or do i need to setup the whole network manually?

**Comment by bmn-m** [comment]
I uploaded the [network](https://github.com/bmn-m/Stormshield-SN300-openwrt/blob/9aba3c631a1eae33ef782679169e59fbc2694ce9/network) file. 
You can use the config file as a template, please note that i have included placeholders for the ip addresses.
